# sql clauses that can be used as a first clause (non-exhaustive)
SQL_STATEMENT_TYPES = [
    "ABORT",
    "ALTER",
    "ANALYZE",
    "ATTACH",
    "BEGIN",
    "CALL",
    "CHECKPOINT",
    "COMMENT ON",
    "COMMIT",
    "COPY",
    "CREATE",
    "DEALLOCATE",
    "DELETE",
    "DESCRIBE",
    "DETACH",
    "DROP",
    "EXECUTE",
    "EXPLAIN",
    "EXPORT",
    "FORCE INSTALL",
    "FORCE CHECKPOINT",
    "FROM",
    "IMPORT",
    "INSERT",
    "INSTALL",
    "LOAD",
    "MERGE INTO",
    "PIVOT",
    "PIVOT_WIDER",
    "PRAGMA",
    "PREPARE",
    "RESET",
    "ROLLBACK",
    "SELECT",
    "SET",
    "SHOW",
    "SUMMARIZE",
    "START TRANSACTION",
    "TRUNCATE",
    "UNPIVOT",
    "UPDATE",
    "USE",
    "VACUUM",
    "VALUES",
    "WITH",
]

# from duckdb/duckdb -> test/sqlite/sqllogic_parser.cpp
SQLLOGIC_COMMANDS = [
    "concurrentforeach",
    "concurrentloop",
    "endloop",
    "foreach",
    "halt",
    "hash-threshold",
    "load",
    "loop",
    "mode",
    "onlyif",
    "query",
    "reconnect",
    "require-env",
    "require",
    "reset",
    "restart",
    "set",
    "skipif",
    "sleep",
    "statement",
    "test-env",
    "unzip",
    "#",
]
