name: Run Afl++ Fuzzer
on:
  push:
  workflow_dispatch:
    inputs:
      duckdbRepo:
        description: 'duckdb repository'
        required: true
        type: string
        default: 'duckdb/duckb'
      ref:
        description: 'ref'
        required: true
        type: string
        default: 'main'
      fuzzer:
        description: 'fuzz scenario'
        required: true
        type: choice
        options:
          - fuzz-csv-multi-param
          - fuzz-json-multi-param
          - fuzz-parquet-multi-param
        default: fuzz-csv-multi-param
      fuzzTime:
        description: 'fuzz time (seconds)'
        required: true
        type: number
        default: 3600

jobs:
  install-aflplusplus:
    name: Install AFL++
    runs-on: ubuntu-24.04

    steps:
      - name: print sha
        run: echo $GITHUB_SHA

      - name: print fuzz scenario
        run: |
          echo ${{ inputs.duckdbRepo }}
          echo ${{ inputs.ref }}
          echo ${{ inputs.fuzzer }}
          echo ${{ inputs.fuzzTime }}
