name: Run Afl++ Fuzzer
on:
  push:
  workflow_dispatch:

jobs:
  install-aflplusplus:
    name: Install AFL++
    runs-on: ubuntu-24.04

    steps:
      - name: print sha
        run: echo $GITHUB_SHA
